version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345678
    ports:
      - 18030:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 18031:8080
